version: '3.6'

services:
  web:
    build:
      context: ./web
    container_name: katyholvey-web
    network_mode: bridge
    volumes:
      - ./web:/home/node
    ports:
      - 35729:35729
    env_file: .env
    environment:
      VIRTUAL_HOST: local.katyholvey.co.uk
