version: '3.6'

services:
  web:
    build:
      context: ./web
    container_name: katyholvey-web
    network_mode: bridge
    volumes:
      - ./web:/home/node
      - /home/node/node_modules
    ports:
      - 3000
      - 35729:35729
    environment:
      VIRTUAL_HOST: local.katyholvey.co.uk
      VIRTUAL_PORT: 3000
