version: '3.6'
services:
  web:
    build:
      context: ./web
    container_name: katyholvey-web
    restart: always
    volumes:
      - ./web:/home/node
      - /home/node/node_modules
    ports:
      - 80:3000
      - 35729:35729
